var data = [
{
  "id": 1,
  "firstName": "Billy",
  "lastName": "Welch",
  "email": "bwelch0@wiley.com",
  "gender": "Male",
  "ssn": "590-84-0503",
  "age": 22
}, {
  "id": 2,
  "firstName": "Heather",
  "lastName": "Henderson",
  "email": "hhenderson1@timesonline.co.uk",
  "gender": "Female",
  "ssn": "344-59-5803",
  "age": 29
}, {
  "id": 3,
  "firstName": "Dorothy",
  "lastName": "Elliott",
  "email": "delliott2@va.gov",
  "gender": "Female",
  "ssn": "351-16-3012",
  "age": 58
}, {
  "id": 4,
  "firstName": "Joan",
  "lastName": "Day",
  "email": "jday3@icq.com",
  "gender": "Female",
  "ssn": "995-28-7192",
  "age": 56
}, {
  "id": 5,
  "firstName": "Robin",
  "lastName": "Murray",
  "email": "rmurray4@simplemachines.org",
  "gender": "Female",
  "ssn": "575-74-3246",
  "age": 64
}, {
  "id": 6,
  "firstName": "Thomas",
  "lastName": "Berry",
  "email": "tberry5@indiatimes.com",
  "gender": "Male",
  "ssn": "958-06-4652",
  "age": 64
}, {
  "id": 7,
  "firstName": "Kimberly",
  "lastName": "Nichols",
  "email": "knichols6@businessweek.com",
  "gender": "Female",
  "ssn": "193-56-1553",
  "age": 69
}, {
  "id": 8,
  "firstName": "Diane",
  "lastName": "Alexander",
  "email": "dalexander7@twitter.com",
  "gender": "Female",
  "ssn": "681-41-4546",
  "age": 34
}, {
  "id": 9,
  "firstName": "Terry",
  "lastName": "Gonzalez",
  "email": "tgonzalez8@cafepress.com",
  "gender": "Male",
  "ssn": "787-58-5294",
  "age": 41
}, {
  "id": 10,
  "firstName": "Wanda",
  "lastName": "Stevens",
  "email": "wstevens9@samsung.com",
  "gender": "Female",
  "ssn": "870-15-0380",
  "age": 24
},
{
  "id": 1,
  "firstName": "Billy",
  "lastName": "Welch",
  "email": "bwelch0@wiley.com",
  "gender": "Male",
  "ssn": "590-84-0503",
  "age": 22
}, {
  "id": 2,
  "firstName": "Heather",
  "lastName": "Henderson",
  "email": "hhenderson1@timesonline.co.uk",
  "gender": "Female",
  "ssn": "344-59-5803",
  "age": 29
},{
  "id": 3,
  "firstName": "Dorothy",
  "lastName": "Elliott",
  "email": "delliott2@va.gov",
  "gender": "Female",
  "ssn": "351-16-3012",
  "age": 58
},{
  "id": 9,
  "firstName": "Terry",
  "lastName": "Gonzalez",
  "email": "tgonzalez8@cafepress.com",
  "gender": "Male",
  "ssn": "787-58-5294",
  "age": 41
}, {
  "id": 10,
  "firstName": "Wanda",
  "lastName": "Stevens",
  "email": "wstevens9@samsung.com",
  "gender": "Female",
  "ssn": "870-15-0380",
  "age": 24
}];